### ISSUE TITLE
Tools installed with tlmgr are not in PATH

### ISSUE THREAD

**Issue by flyx** [reitzig/texlive-docker#12]
When I have e.g. `latexmk` in my `Texlivefile`, I cannot call it after tlmgr installed it because it's not in the PATH.

I did a quick workaround in the entrypoint script by adding:

```
export PATH="${PATH}:/usr/local/texlive/2023/bin/x86_64-linuxmusl"
```

 However this should likely be solved in a future-proof way.

**Comment by reitzig** [comment]
Related: https://github.com/reitzig/texlive-docker/issues/7#issuecomment-1635762141

**Comment by flyx** [comment]
I tested the pre-release with my GitHub workflow, it works flawlessly. Thanks!
