### ISSUE TITLE
Fix credentials for release workflow (to release 2023.1)

### ISSUE THREAD

**Issue by koppor** [reitzig/texlive-docker#2]
The monthly release automation fails, because

See https://github.com/reitzig/texlive-docker/actions/runs/4580266415/jobs/8088841313 for an example

    Will try to create tag release-2023.1 on reitzig/texlive-docker:d2937841b944109856bb26bfdf85895f6a09bd0b

```json
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```

---

I should also write something now and then. Otherwise, workflows are not run due to inactivity:

![image](https://github.com/reitzig/texlive-docker/assets/1366654/876fde48-56f6-4aad-8ef3-2eadd2073aa0)

**Comment by reitzig** [comment]
Yeah, I kinda ignored the numerous mails GitHub sent to warn me about expiring tokens. 🫣

Fixed, and pushed a new release. Thanks for the nudge! 🙏
