### ISSUE TITLE
gpg unavailable

### ISSUE THREAD

**Issue by koppor** [reitzig/texlive-docker#6]
tlmgr: package repository https://ctan.mirrors.hoobly.com/systems/texlive/tlnet (not verified: gpg unavailable)

Would it make sense to add `gpg` to `texlive-base` - or does it consume too much space?

**Comment by reitzig** [comment]
Don't know without trying, but if it's a use case so common it's likely to affect most users, let's add it either way. :) What do you think?

**Comment by reitzig** [comment]
FWIW, it doesn't take too much space at all:

```
$ docker run --rm -it alpine sh
/ # apk add gpg
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/11) Installing libgpg-error (1.45-r0)
(2/11) Installing libassuan (2.5.6-r0)
(3/11) Installing libcap (2.64-r1)
(4/11) Installing ncurses-terminfo-base (6.3_p20220521-r1)
(5/11) Installing ncurses-libs (6.3_p20220521-r1)
(6/11) Installing pinentry (1.2.0-r0)
Executing pinentry-1.2.0-r0.post-install
(7/11) Installing libgcrypt (1.10.1-r0)
(8/11) Installing gnupg-gpgconf (2.2.35-r4)
(9/11) Installing libbz2 (1.0.8-r1)
(10/11) Installing sqlite-libs (3.40.1-r1)
(11/11) Installing gpg (2.2.35-r4)
Executing busybox-1.35.0-r13.trigger
OK: 10 MiB in 25 packages
/ # 
```

I'm open to adding this, but I'd like to understand why, first. Is it "only" so that packages can be verified during install, or are there other uses?

**Comment by reitzig** [comment]
ℹ️ I pushed a "pre-release" [reitzig/texlive-docker@pre-2023.4](https://github.com/reitzig/texlive-docker/releases/tag/pre-2023.4) with these changes, in case you want to test this before month's end.
